import { Navbar } from '@/components/navbar/navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Ysabeau } from 'next/font/google';

const ysabeau = Ysabeau({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={ysabeau.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
